version: '3.7'

services:

  frontend-prod:
    container_name: frontend-prod
    image: europe-west3-docker.pkg.dev/habitivity-363118/hbt-docker/frontend:prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '4000:80'
