version: '3.7'

services:

  frontend-prod:
    container_name: frontend-prod
    image: eu.gcr.io/habitivity-363118/habitivity:prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '4000:80'
