import React from "react";
import {
    BorderOutlined,
    HomeFilled,
    HomeOutlined,
    HomeTwoTone, LogoutOutlined,
    RightCircleOutlined,
    SettingOutlined,
    EditOutlined,
    PlusOutlined,
    RightOutlined,
    DragOutlined,
    RestOutlined,
    LineChartOutlined,
    CalendarOutlined,
    CarryOutOutlined,
} from "@ant-design/icons";

export enum IconType {
    HomeTwoTone = 1,
    HomeFilled,
    HomeOutlined,
    BorderOutlined,
    RightCircleOutlined,
    SettingOutlined,
    LogoutOutlined,
    EditOutlined,
    PlusOutlined,
    RightOutlined,
    DragOutlined,
    RestOutlined,
    LineChartOutlined,
    CalendarOutlined,
    CarryOutOutlined,
}

export const icons: Record<IconType, React.ReactNode> = {
    [IconType.HomeTwoTone]: React.createElement(HomeTwoTone),
    [IconType.HomeFilled]: React.createElement(HomeFilled),
    [IconType.HomeOutlined]: React.createElement(HomeOutlined),
    [IconType.BorderOutlined]: React.createElement(BorderOutlined),
    [IconType.RightCircleOutlined]: React.createElement(RightCircleOutlined),
    [IconType.SettingOutlined]: React.createElement(SettingOutlined),
    [IconType.LogoutOutlined]: React.createElement(LogoutOutlined),
    [IconType.EditOutlined]: React.createElement(EditOutlined),
    [IconType.PlusOutlined]: React.createElement(PlusOutlined),
    [IconType.RightOutlined]: React.createElement(RightOutlined),
    [IconType.DragOutlined]: React.createElement(DragOutlined),
    [IconType.RestOutlined]: React.createElement(RestOutlined),
    [IconType.LineChartOutlined]: React.createElement(LineChartOutlined),
    [IconType.CalendarOutlined]: React.createElement(CalendarOutlined),
    [IconType.CarryOutOutlined]: React.createElement(CarryOutOutlined),
}