import React from 'react';
import {
  BorderOutlined,
  HomeFilled,
  HomeOutlined,
  HomeTwoTone,
  LogoutOutlined,
  RightCircleOutlined,
  SettingOutlined,
  EditOutlined,
  PlusOutlined,
  RightOutlined,
  DragOutlined,
  RestOutlined,
  LineChartOutlined,
  CalendarOutlined,
  CarryOutOutlined,
} from '@ant-design/icons';

export enum IconType {
  HOME_TWO_TONE = 1,
  HOME_FILLED,
  HOME_OUTLINED,
  BORDER_OUTLINED,
  RIGHT_CIRCLE_OUTLINED,
  SETTING_OUTLINED,
  LOGOUT_OUTLINED,
  EDIT_OUTLINED,
  PLUS_OUTLINED,
  RIGHT_OUTLINED,
  DRAG_OUTLINED,
  REST_OUTLINED,
  LINE_CHART_OUTLINED,
  CALENDAR_OUTLINED,
  CARRY_OUT_OUTLINED,
}

export const icons: Record<IconType, React.ReactNode> = {
  [IconType.HOME_TWO_TONE]: React.createElement(HomeTwoTone),
  [IconType.HOME_FILLED]: React.createElement(HomeFilled),
  [IconType.HOME_OUTLINED]: React.createElement(HomeOutlined),
  [IconType.BORDER_OUTLINED]: React.createElement(BorderOutlined),
  [IconType.RIGHT_CIRCLE_OUTLINED]: React.createElement(RightCircleOutlined),
  [IconType.SETTING_OUTLINED]: React.createElement(SettingOutlined),
  [IconType.LOGOUT_OUTLINED]: React.createElement(LogoutOutlined),
  [IconType.EDIT_OUTLINED]: React.createElement(EditOutlined),
  [IconType.PLUS_OUTLINED]: React.createElement(PlusOutlined),
  [IconType.RIGHT_OUTLINED]: React.createElement(RightOutlined),
  [IconType.DRAG_OUTLINED]: React.createElement(DragOutlined),
  [IconType.REST_OUTLINED]: React.createElement(RestOutlined),
  [IconType.LINE_CHART_OUTLINED]: React.createElement(LineChartOutlined),
  [IconType.CALENDAR_OUTLINED]: React.createElement(CalendarOutlined),
  [IconType.CARRY_OUT_OUTLINED]: React.createElement(CarryOutOutlined),
};
